[versions]
agp = "7.3.0"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.9.0"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.13.1"
androidx-espresso-core = "3.5.1"
androidx-material = "1.12.0"
androidx-test-junit = "1.1.5"
androidx-compose = "1.9.0"
androidx-compose-ui = "1.6.7"
compose-plugin = "1.6.10"
junit = "4.13.2"
kotlin = "2.0.0"
ktor = "2.1.3"
realm = "2.0.0"
jvmTarget = "1.8"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.8.0" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }

androidx-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx_compose" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx_compose_ui" }
androidx-compose-material = { group = "androidx.compose.material", name = "material", version.ref = "androidx-appcompat" }

#implementation("androidx.activity:activity-compose:1.9.0")
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor"}
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor"}
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor"}
ktor-client-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor"}
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor"}
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor"}
realm-base = { module = "io.realm.kotlin:library-base", version.ref = "realm" }
realm-sync = { module = "io.realm.kotlin:library-sync", version.ref = "realm" }
realm-plugin = { module = "io.realm.kotlin:gradle-plugin", version.ref = "realm" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
realm = { id = "io.realm.kotlin", version.ref = "realm" }
